### ISSUE TITLE
Rodauth benchmark manipulates files that don't exist

### ISSUE THREAD

**Issue by tenderlove** [easydatawarehousing/ruby_measure_responsetime#2]
Hi,

I'm trying to run the Rodauth benchmark, but config.ru [tries to copy a file that doesn't exist](https://github.com/easydatawarehousing/ruby_measure_responsetime/blob/2727bfcc382761a1416f15dfc13491ca8a00d7b0/apps/rodauth/config.ru#L7), and I can't figure out how to generate that file. Am I running the benchmark incorrectly, or missing something?

Thank you!

**Comment by easydatawarehousing** [comment]
Hi,

You are not missing anything. I should have included this file, the .gitignore filter was a bit too enthousiastic.
Added the file. Please let me know if there are still any problems.
